(DEFUN fib1(n)
    (if (< n 2)
        n
        (+ (fib1 (- n 1)) (fib1 (- n 2)))
    )
)

(DEFUN fib2(n)
    (labels ((fib-in (n a b)
        (if (= n 0)
            a
            (fib-in (- n 1) b (+ a b))
        )))
        (fib-in n 0 1))
)

(format t "Original resursion:")
(trace fib1)
(let ((x (fib1 5)))
    (format t "result: ~A~%" x)
)
(untrace fib1)
(format t "Tail resursion:")
(trace fib2)
(let ((x (fib2 5)))
    (format t "result: ~A~%" x)
)
(untrace fib2)